from_latest_tag = true
ignore_merge_commits = false
ignore_fixup_commits = false
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
generate_mono_repository_package_tags = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false

pre_bump_hooks = [
  '''sed -i "3s/    version = \"[0-9]\.[0-9]\.[0.9]\",/    version = \"{{version}}\",/" MODULE.bazel''',
  "./pre-commit.hook.sh",
  "bazelisk test //... && bazelisk shutdown",
  "cd examples && bazelisk build //... && bazelisk shutdown",
]
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

tag_prefix = "v"

[git_hooks.pre-commit]
script = "./pre-commit.hook.sh"

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
